# install packages
install.packages('ggplot2')
install.packages('dplyr')
install.packages('tidyr')
install.packages('lubridate')
install.packages('survey')
install.packages('reshape2')
install.packages('rmarkdown')
install.packages('xtable')
install.packages('maps')
install.packages('ggmap')
install.packages("devtools")
install.packages('swirl')
install.packages('ggvis')
install.packages('twitteR')
install.packages('streamR')
install.packages('ROAuth')
install.packageS('nhlscrapr')